alter session set "_ORACLE_SCRIPT"=true;  

CREATE USER "BASIC_TEST" IDENTIFIED BY "BASIC_TEST";

ALTER SESSION SET current_schema = BASIC_TEST;



CREATE TABLESPACE BASIC_TEST_TS 
   DATAFILE 'basic_test.dbf' 
   SIZE 10m;
   
ALTER USER BASIC_TEST QUOTA UNLIMITED ON BASIC_TEST_TS;
  
CREATE SEQUENCE BASIC_TEST.HOUSE_SEQ
    	MINVALUE 1
		NOMAXVALUE
		START WITH 1
		INCREMENT BY 1;


CREATE TABLE BASIC_TEST.HOUSE (
    ID INT NOT NULL , 
    OWNER VARCHAR(255), 
    FULLYPAID VARCHAR(1), 
    CONSTRAINT HOUSE_PK PRIMARY KEY (ID)
    ENABLE 
)TABLESPACE BASIC_TEST_TS;

CREATE SEQUENCE BASIC_TEST.ITEM_SEQ
    	MINVALUE 1
		NOMAXVALUE
		START WITH 1
		INCREMENT BY 1;
		
		
CREATE TABLE BASIC_TEST.ITEM (
    ID INT NOT NULL,
    NAME VARCHAR(255),
    HOUSE INT NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ID),
    CONSTRAINT HOUSE_FK FOREIGN KEY(HOUSE)
            REFERENCES BASIC_TEST.HOUSE(ID)
)TABLESPACE BASIC_TEST_TS;
   
GRANT CREATE SESSION TO BASIC_TEST;
GRANT CREATE SEQUENCE TO BASIC_TEST;
GRANT CONNECT TO BASIC_TEST;
GRANT ALL PRIVILEGES ON BASIC_TEST.HOUSE_SEQ TO "BASIC_TEST";
GRANT ALL PRIVILEGES ON BASIC_TEST.ITEM_SEQ TO "BASIC_TEST";