CREATE OR REPLACE PROCEDURE BASIC_TEST()
LANGUAGE plpgsql
AS $$
BEGIN
/*Crear USER*/
CREATE USER BASIC_TEST WITH PASSWORD 'BASIC_TEST';

/*TABLESPACE*/
/*CREATE TABLESPACE BASIC_TABLESPACE
  OWNER BASIC_TEST
  LOCATION '/var*/
  
/*Crear SCHEMA*/
CREATE SCHEMA BASIC_TEST AUTHORIZATION BASIC_TEST;

/*Conectar DATABSE con USER*/
GRANT CONNECT ON DATABASE BASIC_TEST TO BASIC_TEST;

    /*CREAR TABLAS*/
    CREATE TABLE BASIC_TEST.HOUSE
    (
        ID INTEGER NOT NULL ,
        OWNER VARCHAR(255) NOT NULL,
        FULLYPAID BOOLEAN,
        CONSTRAINT HOUSE_PK PRIMARY KEY (ID)
    );
    
    CREATE SEQUENCE BASIC_TEST.HOUSE_SEQ
    	START 0
		INCREMENT 1
		MINVALUE 0
		OWNED BY BASIC_TEST.HOUSE.ID;
    
    CREATE TABLE BASIC_TEST.ITEM
    (
        ID INTEGER NOT NULL, 
        NAME VARCHAR(255),
        HOUSE INTEGER,
        CONSTRAINT ITEM_PK PRIMARY KEY (ID),
        CONSTRAINT HOUSE_FK FOREIGN KEY(HOUSE)
            REFERENCES BASIC_TEST.HOUSE(ID)
    );
    
    CREATE SEQUENCE BASIC_TEST.ITEM_SEQ
    	START 0
		INCREMENT 1
		MINVALUE 0
		OWNED BY BASIC_TEST.ITEM.ID;
    
/*PERMISOS en TABLAS a USER*/
GRANT SELECT, UPDATE, DELETE, INSERT ON BASIC_TEST.HOUSE TO BASIC_TEST;
GRANT SELECT, UPDATE, DELETE, INSERT ON BASIC_TEST.ITEM TO BASIC_TEST;

    
END;
$$;

CALL BASIC_TEST();